services:
  - type: web
    name: edufocus-system
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && cd ../client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.x
